// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hrms_backend.Data;

#nullable disable

namespace hrms_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260218132644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hrms_backend.Models.Entities.Employees", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_employee_id");

                    b.Property<string>("AadharNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankIFSC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("Date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("Date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("RolesId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Jobs.JobReviewers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_job_reviewer_id");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_job_id");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reviewer_id");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("job_reviewers");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Jobs.JobShared", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_job_share_id");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_job_id");

                    b.Property<Guid>("SharedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("shared_by");

                    b.Property<DateTime>("SharedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SharedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("SharedById");

                    b.ToTable("job_shares");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Jobs.Jobs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_job_id");

                    b.Property<string>("AttachedFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("job_id");

                    b.Property<Guid>("PocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("JobCode")
                        .IsUnique();

                    b.HasIndex("PocId");

                    b.HasIndex("PostedById");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Jobs.Referrals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_referral_id");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_job_id");

                    b.Property<Guid>("ReferralById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_referred_by");

                    b.Property<string>("ReferredToCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefferedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referred_to");

                    b.Property<string>("RefferedToEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ReferralById");

                    b.ToTable("job_referrals");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.SystemConfigs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_system_config_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_created_by");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("SystemId")
                        .HasColumnType("int")
                        .HasColumnName("fk_system_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[is_deleted] =0");

                    b.HasIndex("SystemId");

                    b.ToTable("system_configs");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.SystemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_system_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("system_name");

                    b.HasKey("Id");

                    b.ToTable("system_info");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Travel.EmployeeTravelDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_etd_id");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expense_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("owner_type");

                    b.Property<Guid>("TravelExpenseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_expense_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("TravelExpenseId")
                        .IsUnique();

                    b.ToTable("employee_travel_documents");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Travel.HrTravelDocuments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_htd_id");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("owner_type");

                    b.Property<Guid>("TravelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_travel_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploaded_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("TravelId");

                    b.HasIndex("UploadedById");

                    b.ToTable("hr_travel_documents");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Travel.TravelAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_ta_id");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_employee_id");

                    b.Property<Guid?>("EmployeesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("TravelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_travel_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeesId");

                    b.HasIndex("TravelId");

                    b.ToTable("travel_allocations");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Travel.TravelExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_expense_id");

                    b.Property<Guid>("AllocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fk_allocation_id");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expense_date");

                    b.Property<string>("HrRemarks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hr_remarks");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expense_status");

                    b.Property<long>("TotalAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("total_expense");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[is_deleted] =0");

                    b.ToTable("travel_expenses");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Travel.TravelPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pk_travel_id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IsDeleted")
                        .HasFilter("[is_deleted] =0");

                    b.ToTable("travel_plan");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Employees", b =>
                {
                    b.HasOne("hrms_backend.Models.Entities.Employees", "Manager")
                        .WithMany("Reports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("hrms_backend.Models.Entities.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Jobs.JobReviewers", b =>
                {
                    b.HasOne("hrms_backend.Models.Entities.Jobs.Jobs", "Job")
                        .WithMany("JobReviewers")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hrms_backend.Models.Entities.Employees", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Jobs.JobShared", b =>
                {
                    b.HasOne("hrms_backend.Models.Entities.Jobs.Jobs", "Job")
                        .WithMany("JobShared")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hrms_backend.Models.Entities.Employees", "SharedBy")
                        .WithMany()
                        .HasForeignKey("SharedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("SharedBy");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Jobs.Jobs", b =>
                {
                    b.HasOne("hrms_backend.Models.Entities.Employees", "Poc")
                        .WithMany()
                        .HasForeignKey("PocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hrms_backend.Models.Entities.Employees", "PostedBy")
                        .WithMany()
                        .HasForeignKey("PostedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Poc");

                    b.Navigation("PostedBy");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Jobs.Referrals", b =>
                {
                    b.HasOne("hrms_backend.Models.Entities.Jobs.Jobs", "Job")
                        .WithMany("Referrals")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hrms_backend.Models.Entities.Employees", "RefferedBy")
                        .WithMany()
                        .HasForeignKey("ReferralById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("RefferedBy");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("hrms_backend.Models.Entities.Employees", "Employee")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.SystemConfigs", b =>
                {
                    b.HasOne("hrms_backend.Models.Entities.Employees", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hrms_backend.Models.Entities.SystemInfo", "System")
                        .WithMany("SystemConfigs")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("System");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Travel.EmployeeTravelDocument", b =>
                {
                    b.HasOne("hrms_backend.Models.Entities.Travel.TravelExpense", "TravelExpense")
                        .WithOne("EmployeeTravelDocuments")
                        .HasForeignKey("hrms_backend.Models.Entities.Travel.EmployeeTravelDocument", "TravelExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelExpense");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Travel.HrTravelDocuments", b =>
                {
                    b.HasOne("hrms_backend.Models.Entities.Travel.TravelPlan", "TravelPlan")
                        .WithMany("HrTravelDocuments")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hrms_backend.Models.Entities.Employees", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelPlan");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Travel.TravelAllocation", b =>
                {
                    b.HasOne("hrms_backend.Models.Entities.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hrms_backend.Models.Entities.Employees", null)
                        .WithMany("TravelAllocations")
                        .HasForeignKey("EmployeesId");

                    b.HasOne("hrms_backend.Models.Entities.Travel.TravelPlan", "TravelPlan")
                        .WithMany("TravelAllocation")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TravelPlan");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Travel.TravelExpense", b =>
                {
                    b.HasOne("hrms_backend.Models.Entities.Travel.TravelAllocation", "TravelAllocation")
                        .WithMany()
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hrms_backend.Models.Entities.Employees", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedBy");

                    b.Navigation("TravelAllocation");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Travel.TravelPlan", b =>
                {
                    b.HasOne("hrms_backend.Models.Entities.Employees", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Employees", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Reports");

                    b.Navigation("TravelAllocations");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Jobs.Jobs", b =>
                {
                    b.Navigation("JobReviewers");

                    b.Navigation("JobShared");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.SystemInfo", b =>
                {
                    b.Navigation("SystemConfigs");
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Travel.TravelExpense", b =>
                {
                    b.Navigation("EmployeeTravelDocuments")
                        .IsRequired();
                });

            modelBuilder.Entity("hrms_backend.Models.Entities.Travel.TravelPlan", b =>
                {
                    b.Navigation("HrTravelDocuments");

                    b.Navigation("TravelAllocation");
                });
#pragma warning restore 612, 618
        }
    }
}
